# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blox/options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blox/options.proto',
  package='blox.options',
  serialized_pb=_b('\n\x12\x62lox/options.proto\x12\x0c\x62lox.options\x1a google/protobuf/descriptor.proto:7\n\x0eis_constructor\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\x08:7\n\x0euse_dictionary\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd4\x03 \x01(\x08:?\n\x16use_dictionary_package\x12\x1d.google.protobuf.FieldOptions\x18\xe2\xd4\x03 \x01(\t:5\n\x0cmap_with_key\x12\x1d.google.protobuf.FieldOptions\x18\xe3\xd4\x03 \x01(\t:0\n\x07inlined\x12\x1d.google.protobuf.FieldOptions\x18\xe4\xd4\x03 \x01(\x08:,\n\x03set\x12\x1d.google.protobuf.FieldOptions\x18\xe5\xd4\x03 \x01(\x08:3\n\x08lifetime\x12\x1f.google.protobuf.MessageOptions\x18\xf0\xa2\x04 \x01(\tB$\n\"com.logicblox.common.protocol.blox')
  ,
  dependencies=[google.protobuf.descriptor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


IS_CONSTRUCTOR_FIELD_NUMBER = 60000
is_constructor = _descriptor.FieldDescriptor(
  name='is_constructor', full_name='blox.options.is_constructor', index=0,
  number=60000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
USE_DICTIONARY_FIELD_NUMBER = 60001
use_dictionary = _descriptor.FieldDescriptor(
  name='use_dictionary', full_name='blox.options.use_dictionary', index=1,
  number=60001, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
USE_DICTIONARY_PACKAGE_FIELD_NUMBER = 60002
use_dictionary_package = _descriptor.FieldDescriptor(
  name='use_dictionary_package', full_name='blox.options.use_dictionary_package', index=2,
  number=60002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MAP_WITH_KEY_FIELD_NUMBER = 60003
map_with_key = _descriptor.FieldDescriptor(
  name='map_with_key', full_name='blox.options.map_with_key', index=3,
  number=60003, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
INLINED_FIELD_NUMBER = 60004
inlined = _descriptor.FieldDescriptor(
  name='inlined', full_name='blox.options.inlined', index=4,
  number=60004, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SET_FIELD_NUMBER = 60005
set = _descriptor.FieldDescriptor(
  name='set', full_name='blox.options.set', index=5,
  number=60005, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
LIFETIME_FIELD_NUMBER = 70000
lifetime = _descriptor.FieldDescriptor(
  name='lifetime', full_name='blox.options.lifetime', index=6,
  number=70000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['is_constructor'] = is_constructor
DESCRIPTOR.extensions_by_name['use_dictionary'] = use_dictionary
DESCRIPTOR.extensions_by_name['use_dictionary_package'] = use_dictionary_package
DESCRIPTOR.extensions_by_name['map_with_key'] = map_with_key
DESCRIPTOR.extensions_by_name['inlined'] = inlined
DESCRIPTOR.extensions_by_name['set'] = set
DESCRIPTOR.extensions_by_name['lifetime'] = lifetime

google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(is_constructor)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(use_dictionary)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(use_dictionary_package)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(map_with_key)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(inlined)
google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(set)
google.protobuf.descriptor_pb2.MessageOptions.RegisterExtension(lifetime)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.logicblox.common.protocol.blox'))
# @@protoc_insertion_point(module_scope)
