# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blox/connect/Exception.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blox/connect/Exception.proto',
  package='blox.connect',
  serialized_pb=_b('\n\x1c\x62lox/connect/Exception.proto\x12\x0c\x62lox.connect\"Z\n\x12\x45xceptionContainer\x12\x0f\n\x07message\x18\x01 \x02(\t\x12\x33\n\tworkspace\x18\x02 \x01(\x0b\x32 .blox.connect.WorkspaceException\"\x87\x01\n\x12WorkspaceException\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x33\n\x04\x63ode\x18\x02 \x02(\x0e\x32%.blox.connect.WorkspaceException.Code\".\n\x04\x43ode\x12\x12\n\x0e\x44OES_NOT_EXIST\x10\x01\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x02\x42,\n\x15\x63om.logicblox.connectB\x11ProtoBufExceptionH\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_WORKSPACEEXCEPTION_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='blox.connect.WorkspaceException.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOES_NOT_EXIST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_EXISTS', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=228,
  serialized_end=274,
)
_sym_db.RegisterEnumDescriptor(_WORKSPACEEXCEPTION_CODE)


_EXCEPTIONCONTAINER = _descriptor.Descriptor(
  name='ExceptionContainer',
  full_name='blox.connect.ExceptionContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='blox.connect.ExceptionContainer.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='blox.connect.ExceptionContainer.workspace', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=136,
)


_WORKSPACEEXCEPTION = _descriptor.Descriptor(
  name='WorkspaceException',
  full_name='blox.connect.WorkspaceException',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='blox.connect.WorkspaceException.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='blox.connect.WorkspaceException.code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKSPACEEXCEPTION_CODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=274,
)

_EXCEPTIONCONTAINER.fields_by_name['workspace'].message_type = _WORKSPACEEXCEPTION
_WORKSPACEEXCEPTION.fields_by_name['code'].enum_type = _WORKSPACEEXCEPTION_CODE
_WORKSPACEEXCEPTION_CODE.containing_type = _WORKSPACEEXCEPTION
DESCRIPTOR.message_types_by_name['ExceptionContainer'] = _EXCEPTIONCONTAINER
DESCRIPTOR.message_types_by_name['WorkspaceException'] = _WORKSPACEEXCEPTION

ExceptionContainer = _reflection.GeneratedProtocolMessageType('ExceptionContainer', (_message.Message,), dict(
  DESCRIPTOR = _EXCEPTIONCONTAINER,
  __module__ = 'blox.connect.Exception_pb2'
  # @@protoc_insertion_point(class_scope:blox.connect.ExceptionContainer)
  ))
_sym_db.RegisterMessage(ExceptionContainer)

WorkspaceException = _reflection.GeneratedProtocolMessageType('WorkspaceException', (_message.Message,), dict(
  DESCRIPTOR = _WORKSPACEEXCEPTION,
  __module__ = 'blox.connect.Exception_pb2'
  # @@protoc_insertion_point(class_scope:blox.connect.WorkspaceException)
  ))
_sym_db.RegisterMessage(WorkspaceException)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.logicblox.connectB\021ProtoBufExceptionH\001'))
# @@protoc_insertion_point(module_scope)
