<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wf</string>
	</array>
	<key>name</key>
	<string>lb-workflow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>A block comment.</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A single line comment.</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.single</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Language keywords</string>
			<key>match</key>
			<string>((^|\s)import\s|(^|\s)synchronizer\s|(^|\s)task\s|(^|\s)workflow\s|(^|\s)main\s|(^|\s)main\(|extends\s)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Restartable composition</string>
			<key>match</key>
			<string>\srestartable\s</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Restartable composition with cleanup</string>
			<key>match</key>
			<string>\s*\}\s*(with)\s*(cleanup)\s*\{</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Sequential composition</string>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Parallel composition</string>
			<key>match</key>
			<string>\|\|</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Forall composition</string>
			<key>match</key>
			<string>(forall)\s*\(\s*[a-zA-Z0-9_]+\s*(in)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Forall composition with max setting</string>
			<key>match</key>
			<string>(forall)\s*&lt;\s*(max)\s*=\s*[a-zA-Z0-9_]+\s*&gt;\(\s*[a-zA-Z0-9_]+\s*(in)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Variable reference in string template</string>
					<key>match</key>
					<string>\$\([a-zA-Z0-9_]+\)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Predicate literal in string template</string>
					<key>match</key>
					<string>\$\(`[a-zA-Z0-9_:]+\)</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Escaping in string template</string>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.other</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A $ is not allowed in strings</string>
					<key>match</key>
					<string>\$</string>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variable reference</string>
			<key>match</key>
			<string>\$[a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Predicate literal</string>
			<key>match</key>
			<string>`[a-zA-Z0-9_:]+</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean values.</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Output binding</string>
			<key>match</key>
			<string>&lt;~</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>An integer constant.</string>
			<key>match</key>
			<string>\b\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Separator</string>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Decorators</string>
			<key>match</key>
			<string>\?|\*</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instance variable container</string>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameter type declaration</string>
			<key>match</key>
			<string>(:)\s*([a-zA-Z0-9_]+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>All task processes under the lb namespace.</string>
			<key>match</key>
			<string>\b(lb.[\w.]*)|BaseTask</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>State machine decorated transition</string>
			<key>match</key>
			<string>(\.)([a-zA-Z0-9_]+)(:)(!?)([a-zA-Z0-9_]+)\s*(-&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>State machine non-decorated transition</string>
			<key>match</key>
			<string>(\.)(!?)([a-zA-Z0-9_]+)\s*(-&gt;)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wf</string>
	<key>uuid</key>
	<string>84d513d5-c3d8-41b0-b69e-b77d7593bcd1</string>
</dict>
</plist>
