<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>logic</string>
	</array>
	<key>name</key>
	<string>LogicBlox</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>A block comment.</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A single line comment.</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.single</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>An integer constant.</string>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Real numbers.</string>
			<key>match</key>
			<string>\d+(.\d+){,1}[eE][+-]{,1}\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean values.</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LogicBlox Symbol</string>
			<key>match</key>
			<string>`[a-zA-Z_:]+(\d|\a)*\b</string>
			<key>name</key>
			<string>entity.name.type.logicblox</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constraint</string>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Level 1 Constraint</string>
			<key>match</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rule</string>
			<key>match</key>
			<string>&lt;-</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Level 1 Rule</string>
			<key>match</key>
			<string>&lt;--</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Terminator</string>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Negation</string>
			<key>match</key>
			<string>!</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Conjunction</string>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Disjunction</string>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Equality</string>
			<key>match</key>
			<string>&lt;=|&gt;=|!=|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Equality</string>
			<key>match</key>
			<string>@</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Arithmetic operations</string>
			<key>match</key>
			<string>\+|-|\*|/</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Colon colon</string>
			<key>match</key>
			<string>::</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(agg\s*&lt;&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Aggregations</string>
			<key>end</key>
			<string>(&gt;&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>All the lang system predicates</string>
			<key>match</key>
			<string>\b(lang:[\w:]*)</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Module keywords</string>
			<key>match</key>
			<string>(export|sealed|clauses|block|alias)\s*\((?=`)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A predicate name.</string>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z_0-9:]*(@prev|@init|@final)?(?=(\(|\[))</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A variable to a functional predicate.</string>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z_0-9]*|_)\s*(?=(,|\.|&lt;-|-&gt;|\)|\]|=))</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.logic</string>
	<key>uuid</key>
	<string>59bf5022-e261-453f-b1cb-9f9fa0712413</string>
</dict>
</plist>
